name: GitHub Repo Stats
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  push:
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          user: Dhahd
          template: classic
          base: header, repositories
          config_timezone: UTC
